
export const dongmanSource = [
  {
    title: '刀剑神域 Alicization' ,
    key: 'dongman0',
    href:"/dongman/0",
    img: 'http://p.xiaomingming.org/FileUpload/201810618424440146.jpg',
    fengge: '小说改/热血/奇幻/战斗/励志',
    kbsj: '2018-10-07',
    gengxin:'已完结, 全24话',
    jianjie:'“这里是哪儿”察觉到的时候，桐人不知为什么陷入了庞大的幻想风格虚拟世界。登录前的记忆模糊不清，只得在周围徘徊寻找线索。之后，他同一名少年相遇了。“我的名字是尤吉欧。请多关照，桐人君。”少年是在虚拟世界的居民，即“NPC”，但是却如同人类一样“感情丰富”。在和尤吉欧加深交往的同时，桐人也在摸索着登出这个世界的方法。在桐人的脑海中，某一个记忆苏醒了。那是幼年时的桐人和尤吉欧在山野奔跑的记忆——不可能存在的记忆。在那个回忆中，有着一个金发少女的身影。她的名字，是爱丽丝，是绝对不应该忘记的、重要的名字。',
    player: [
      <iframe id="play2" src="https://saas.jialingmm.net/code.php?type=flv&amp;vid=https://gss3.baidu.com/6LZ0ej3k1Qd3ote6lo7D0j9wehsv/tieba-smallvideo/60_3f1e68569764aa16faf50e0c4b31a670.mp4&amp;userlink=http%3A%2F%2Fwww.imomoe.io%2Fplayer%2F1615-0-0.html&amp;adress=HuBei_WuHan" border="0" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" allowfullscreen="true" style={{ width: '100%', height: '100%'}}></iframe>,
      <iframe id="play2" src="https://saas.jialingmm.net/code.php?type=flv&amp;vid=https://gss3.baidu.com/6LZ0ej3k1Qd3ote6lo7D0j9wehsv/tieba-smallvideo/60_3f1e68569764aa16faf50e0c4b31a670.mp4&amp;userlink=http%3A%2F%2Fwww.imomoe.io%2Fplayer%2F1615-0-0.html&amp;adress=HuBei_WuHan" border="0" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" allowfullscreen="true" style={{ width: '100%', height: '100%'}}></iframe>,
      <iframe id="play2" src="https://saas.jialingmm.net/code.php?type=flv&amp;vid=https://gss3.baidu.com/6LZ0ej3k1Qd3ote6lo7D0j9wehsv/tieba-smallvideo/60_b00f7f316f37b6818e6d3ab1945d35a3.mp4&amp;userlink=http%3A%2F%2Fwww.imomoe.io%2Fplayer%2F1615-0-1.html&amp;adress=HuBei_WuHan" border="0" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" allowfullscreen="true" style={{ width: '100%', height: '100%'}}></iframe>,
      <iframe id="play2" src="https://saas.jialingmm.net/code.php?type=flv&amp;vid=https://gss3.baidu.com/6LZ0ej3k1Qd3ote6lo7D0j9wehsv/tieba-smallvideo/60_9f2ebcf5a74653fb4c2b942e6bb5ea5d.mp4&amp;userlink=http%3A%2F%2Fwww.imomoe.io%2Fplayer%2F1615-0-2.html&amp;adress=HuBei_WuHan" border="0" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" allowfullscreen="true" style={{ width: '100%', height: '100%'}}></iframe>,
      <iframe id="play2" src="https://saas.jialingmm.net/code.php?type=flv&amp;vid=https://gss3.baidu.com/6LZ0ej3k1Qd3ote6lo7D0j9wehsv/tieba-smallvideo/60_6fe1009d7becb6f384a51d08580da32c.mp4&amp;userlink=http%3A%2F%2Fwww.imomoe.io%2Fplayer%2F1615-0-3.html&amp;adress=HuBei_WuHan" border="0" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" allowfullscreen="true" style={{ width: '100%', height: '100%'}}></iframe>,
      <iframe id="play2" src="https://saas.jialingmm.net/code.php?type=flv&amp;vid=https://gss3.baidu.com/6LZ0ej3k1Qd3ote6lo7D0j9wehsv/tieba-smallvideo/60_05dddc873db3bae5c471ffa8257bab43.mp4&amp;userlink=http%3A%2F%2Fwww.imomoe.io%2Fplayer%2F1615-0-4.html&amp;adress=HuBei_WuHan" border="0" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" allowfullscreen="true" style={{ width: '100%', height: '100%'}}></iframe>,
      <iframe id="play2" src="https://saas.jialingmm.net/code.php?type=flv&amp;vid=https://gss3.baidu.com/6LZ0ej3k1Qd3ote6lo7D0j9wehsv/tieba-smallvideo/60_54935d978ee70af3c994cddc026e1a6e.mp4&amp;userlink=http%3A%2F%2Fwww.imomoe.io%2Fplayer%2F1615-0-5.html&amp;adress=HuBei_WuHan" border="0" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" allowfullscreen="true" style={{ width: '100%', height: '100%'}}></iframe>,
      <iframe id="play2" src="https://saas.jialingmm.net/code.php?type=flv&amp;vid=https://gss3.baidu.com/6LZ0ej3k1Qd3ote6lo7D0j9wehsv/tieba-smallvideo/60_c19e698fd0546754db363010438195c0.mp4&amp;userlink=http%3A%2F%2Fwww.imomoe.io%2Fplayer%2F1615-0-6.html&amp;adress=HuBei_WuHan" border="0" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" allowfullscreen="true" style={{ width: '100%', height: '100%'}}></iframe>,
    ]
  },
  {
    title: "某科学的超电磁炮S",
    key: 'dongman1',
    href:"/dongman/1",
    img: 'http://pic.xiaomingming.org/FileUpload/2561.jpg',
    fengge: '校园/战斗/奇幻',
    kbsj: '2013-04-12',
    gengxin:'已完结, 全24话',
    jianjie:'《某科学的超电磁炮S》讲述根据日本小说家镰池和马原作，漫画家冬川基作画的漫画《科学超电磁炮》改编的动画作品，亦是动画《科学超电磁炮》的第2期动画。原作漫画是以轻小说《魔法禁书目录》中的人物御坂美琴为主人公而展开的故事，作为动画第二期的《科学超电磁炮S》则以漫画版妹妹篇剧情为主线。',
    player: [

    ]
  },
  {
    title: "JOJO的奇妙冒险:黄金之风",
    key: 'dongman2',
    href:"/dongman/2",
    img: 'http://p.xiaomingming.org/FileUpload/201810520592648355.jpg',
    fengge: '热血/智斗/战斗/漫画改',
    kbsj: '2018-10-06',
    gengxin:'连载中, 每周六1:35更新',
    jianjie:'《JOJO的奇妙冒险第五部》讲述住在意大利那不勒斯的青年乔鲁诺乔巴拿，是继承了乔斯达家宿敌DIO之血脉的儿子。 幼年时遭受迫害而自暴自弃的他，由于拯救了一名黑帮男子，而学到了相信他人。不忘恩义、带着敬意对待自己的黑帮，让他的心变得率直。就这样，乔鲁诺开始对黑帮明星怀有憧憬。15岁的乔鲁诺，与统领意大利黑社会的黑帮组织热情一同引发事端，并成为被盯上的目标...',
    player: [
      null, null, <iframe id="play2" src="https://saas.jialingmm.net/code.php?type=flv&amp;vid=https://gss3.baidu.com/6LZ0ej3k1Qd3ote6lo7D0j9wehsv/tieba-smallvideo-transcode/304680130_25560f71fc7064ee08e886398b0d0031_0.mp4&amp;userlink=http%3A%2F%2Fwww.imomoe.io%2Fplayer%2F7587-0-2.html&amp;adress=HuBei_WuHan" border="0" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" allowfullscreen="true" style={{width:'100%',height:'100%'}}></iframe>,
      <iframe id="play2" src="https://saas.jialingmm.net/code.php?type=flv&amp;vid=https://gss3.baidu.com/6LZ0ej3k1Qd3ote6lo7D0j9wehsv/tieba-smallvideo-transcode/324221783_f8695f40897999fd453a56a010d450b2_0.mp4&amp;userlink=http%3A%2F%2Fwww.imomoe.io%2Fplayer%2F7587-0-3.html&amp;adress=HuBei_WuHan" border="0" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" allowfullscreen="true" style={{width:'100%',height:'100%'}}></iframe>
    ]
  },
  {
    title: "Fate/Stay Night",
    key: 'dongman3',
    href:"/dongman/3",
    img: 'http://pic.xiaomingming.org/FileUpload/5279.jpg',
    fengge: '奇幻/热血',
    gengxin:'已完结, 全13话',
    kbsj:'2015-04-04',
    jianjie:'《命运之夜》讲述圣杯是传说中可实现持有者一切愿望的宝物。而为了得到圣杯的仪式就被称为圣杯战争。 参加圣杯战争的7名由圣杯选出的魔术师被称为Master，与7名被称为Servant的使魔订定契约。他们是由圣杯选择的七位英灵，被分为七个职阶，以使魔的身份被召唤出来。能获得圣杯的只有一组，这7组人马各自为了成为最后的那一组而互相残杀。',
    player: [

    ]
  },
  {
    title: "鬼灭之刃",
    key: 'dongman4',
    href:"/dongman/4",
    img: 'http://p.xiaomingming.org/FileUpload/2018642252794002.jpg',
    fengge: '漫画改/战斗/热血/声控/励志',
    kbsj: '2019-04-07',
    gengxin:'连载中, 每周日 00:00更新',
    jianjie:'大正时期，日本。心地善良的卖炭少年·炭治郎，有一天他的家人被鬼杀死了。而唯一幸存下来的妹妹——祢豆子变成了鬼。被绝望的现实打垮的炭治郎，为了寻找让妹妹变回人类的方法，决心朝着“鬼杀队”的道路前进。 人与鬼交织的悲哀的兄妹的故事，现在开始！ ',
    player:[
      <iframe id="play2" src="https://saas.jialingmm.net/code.php?type=flv&amp;vid=http://quan.qq.com/video/1098_83da696b9335ef42ae1c73ef2a5c4803&amp;userlink=http%3A%2F%2Fwww.imomoe.io%2Fplayer%2F7498-0-0.html&amp;adress=HuBei_WuHan" border="0" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" allowfullscreen="true" style={{width:'100%',height:'100%'}}></iframe>,
      <iframe id="play2" src="https://saas.jialingmm.net/code.php?type=flv&amp;vid=http://quan.qq.com/video/1098_46b82913f6dab972429629761b5bd95f&amp;userlink=http%3A%2F%2Fwww.imomoe.io%2Fplayer%2F7498-0-1.html&amp;adress=HuBei_WuHan" border="0" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" allowfullscreen="true" style={{width:'100%',height:'100%'}}></iframe>,
      <iframe id="play2" src="https://saas.jialingmm.net/code.php?type=flv&amp;vid=http://quan.qq.com/video/1098_35a64335905c3eae71444a1369417477&amp;userlink=http%3A%2F%2Fwww.imomoe.io%2Fplayer%2F7498-0-2.html&amp;adress=HuBei_WuHan" border="0" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" allowfullscreen="true" style={{width:'100%',height:'100%'}}></iframe>,
    ]
  },
  {
    title: "盾之勇者成名录",
    key: 'dongman5',
    href:"/dongman/5",
    img: 'http://p.xiaomingming.org/FileUpload/201762221155776184.jpg',
    fengge: '小说改/奇幻/魔法',
    kbsj: '2019-01-02',
    gengxin:'连载中, 每周三22:00更新',
    jianjie:'《盾之勇者成名录》讲述改编自アネコ ユサギ原作小说，讲述作为盾之勇者被召唤至异世界的岩谷尚文。 谁知展开冒险才到第三天就被战友背叛，一口气失去了身为勇者的名声及所有盘缠。为什么只有我碰上这种倒霉事啊！？ 不信任、疑念、猜忌，世界上的所有人事物都是仇敌！ 尚文陷入再也无法相信他人的状态，此时却见一名少女出现在他面前！？ 在苦恼的尽头，他所得到的究竟是什么东西呢！？',
    player: [
      <iframe id="play2" src="https://saas.jialingmm.net/code.php?type=flv&amp;vid=https://gss3.baidu.com/6lz0ej3k1qd3ote6lo7d0j9wehsv/tieba-smallvideo/4_65ce09c59efd093d3e810c4b095af324.mp4&amp;userlink=http%3A%2F%2Fwww.imomoe.io%2Fplayer%2F7062-0-0.html&amp;adress=HuBei_WuHan" border="0" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" allowfullscreen="true" style={{width:'100%',height:'100%'}}></iframe>,
      <iframe id="play2" src="https://saas.jialingmm.net/code.php?type=flv&amp;vid=https://gss3.baidu.com/6lz0ej3k1qd3ote6lo7d0j9wehsv/tieba-smallvideo/3_f76c26abe715c73ad082134b1b5e59d5.mp4&amp;userlink=http%3A%2F%2Fwww.imomoe.io%2Fplayer%2F7062-0-1.html&amp;adress=HuBei_WuHan" border="0" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" allowfullscreen="true" style={{width:'100%',height:'100%'}}></iframe>,
      <iframe id="play2" src="https://saas.jialingmm.net/code.php?type=flv&amp;vid=https://gss3.baidu.com/6lz0ej3k1qd3ote6lo7d0j9wehsv/tieba-smallvideo/3_033d52d3a37d585ab0872b730fbe6a24.mp4&amp;userlink=http%3A%2F%2Fwww.imomoe.io%2Fplayer%2F7062-0-2.html&amp;adress=HuBei_WuHan" border="0" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" allowfullscreen="true" style={{width:'100%',height:'100%'}}></iframe>
    ]
  },
  {
    title: "贤者之孙",
    key: 'dongman6',
    href:"/dongman/6",
    img: 'http://p.xiaomingming.org/FileUpload/201792220351714082.jpg',
    fengge: '小说改/奇幻',
    kbsj: '2019-04-10',
    gengxin:'连载中, 每周三 23:30更新',
    jianjie:'《《贤者之孙》讲述改编自由吉冈刚著作，菊池政治负责插画的轻小说。本应已在事故中死去的青年，却以婴儿的姿态在异世界转生了！然后被救国的英雄「贤者」梅林・沃尔福德所拾救的他，贤者将其取名为「辛」。辛被梅林作为孙子养育成人并吸收了其技术、掌握了惊人的能力。在辛十五岁时，爷爷恍悟自己「忘记教授他常识了」!就这样，为了学习常识并交到朋友，辛入学了亚尔斯海德高等魔法学院以超规格的少年之姿开拓的异世界奇幻生活，由此开幕!!',
    player: [
      <iframe id="play2" src="https://saas.jialingmm.net/code.php?type=flv&amp;vid=http://quan.qq.com/video/1098_c782fa4fe6e3ba2d4c9b02e23d86149b&amp;userlink=http%3A%2F%2Fwww.imomoe.io%2Fplayer%2F7190-0-0.html&amp;adress=HuBei_WuHan" border="0" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" allowfullscreen="true" style={{width:'100%',height:'100%'}}></iframe>,
      <iframe id="play2" src="https://saas.jialingmm.net/code.php?type=flv&amp;vid=http://quan.qq.com/video/1098_8e5ada8fc9f914b74d369caa87f2896f&amp;userlink=http%3A%2F%2Fwww.imomoe.io%2Fplayer%2F7190-0-1.html&amp;adress=HuBei_WuHan" border="0" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" allowfullscreen="true" style={{width:'100%',height:'100%'}}></iframe>,
    ]
  },
  {
    title: "多罗罗",
    key: 'dongman7',
    href:"/dongman/7",
    img: 'http://pic.xiaomingming.org/FileUpload/2561.jpg',
    fengge: '热血/战斗',
    kbsj: '2019-01-06',
    gengxin:'连载中, 每周一22:00更新',
    jianjie:'《新多罗罗》讲述改编自手冢治虫所画的漫画，是继1969年之后再次TV动画化。讲述古日本的室町时代中叶，经历了应仁、文明等动乱之后，当权的足利幕府的威信大幅的动摇，是个君不君臣不臣的时代。武士醍醐景光梦想称霸乱世，于是将尚未出生的儿子献祭给48个魔神，并在缺了48个器官的儿子出生后，将其抛入河中。 孩子被医生寿海救起，为其制作了义眼、义肢等补足了身上所缺乏的部位，并抚养他长大。由于孩子的特殊体质，使得他非常容易引来恶灵，将可能危害抚育他的寿海。二人意识到这点后，孩子决定离开养父去寻找安身之处。临行前寿海给他起名为百鬼丸。 百鬼丸得知自己的器官被48魔神夺去后，为了拿回他们便出发讨伐魔神，途中遇上自称大盗的少年（在第四卷中得知其实是女生）盗贼多罗罗，展开与妖怪战斗的冒险。',
    player: [
      <iframe id="play2" src="https://saas.jialingmm.net/code.php?type=flv&amp;vid=https://gss3.baidu.com/6LZ0ej3k1Qd3ote6lo7D0j9wehsv/tieba-smallvideo/60_a1723ed4c94e4f2b5014ccf8cb2da50b.mp4&amp;userlink=http%3A%2F%2Fwww.imomoe.io%2Fplayer%2F7423-0-0.html&amp;adress=HuBei_WuHan" border="0" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" allowfullscreen="true" style={{width:'100%',height:'100%'}}></iframe>,
    ]
  },
  {
    title: "川柳少女",
    key: 'dongman8',
    href:"/dongman/8",
    img: 'http://p.xiaomingming.org/FileUpload/2019224152489790.jpg',
    fengge: '漫画改/恋爱/校园/日常',
    kbsj: '2019-04-06',
    gengxin:'连载中, 每周六 02:10更新',
    jianjie:'《川柳少女》讲述改编自五十岚正邦创作的同名漫画，将想要说的话以五七五的川柳来表达的女孩子雪白七七子，与外表可怕但内心善良的文艺社学生毒岛英二。由短短17个音节而编织成的两人的日常，无论何时都充满幸福！',
    player:[]
  },
  {
    title: "我们无法一起学习",
    key: 'dongman9',
    href:"/dongman/9",
    img: 'http://p.xiaomingming.org/FileUpload/201882720371633353.jpg',
    fengge: '漫画改/日常/校园/恋爱',
    kbsj: '2019-04-07',
    gengxin:'连载中, 每周日 01:00更新 ',
    jianjie:'《我们无法一起学习》讲述由筒井大志原作漫画改编。高三学生唯我成幸家境贫穷，身为长子的他，一心想获得校内提供的特别VIP推荐资格以进入好大学，同时在将来找到好工作，以此养活一家五口。 某天，学园长突然召见他，并以推荐资格为条件任命他为「教育员」，负责教导两名天才少女．绪方理珠和古桥文乃，本以为事情容易，然而，在一问之下才知道，没想理科天才绪方理珠想考文科大学，而文科天才古桥文乃则想考理科大学！ 面对这艰钜的任务，唯我成幸该如何是好？',
    player:[]
  },
  {
    title: "文豪野犬第三季",
    key: 'dongman10',
    href:"/dongman/10",
    img: 'http://p.xiaomingming.org/FileUpload/20187211813290419.jpg',
    fengge: '漫画改/战斗/奇幻',
    kbsj: '2019-04-12',
    gengxin:'连载中, 每周五 21:30更新',
    jianjie:'《《文豪野犬第三季》讲述以现代横滨为舞台讲述文豪们的超能力战斗！！ 被孤儿院赶出，因为饥饿昏倒在旅途中的少年中岛敦救出了企图自杀的名为太宰治的青年。在听说太宰所属的组织武装侦探社正在追捕为害一方的猛兽食人虎时，敦意外地露出了惊惧的神情食人虎与敦有什么关系？侦探们将如何捕捉它？后续又会有怎样的发展？ 一场引人入胜的故事由此揭开 万般皆注定，身入此镇中...',
    player:[],
  },
  {
    title: "一个人的○○小日子",
    key: 'dongman11',
    href:"/dongman/11",
    img: 'http://p.xiaomingming.org/FileUpload/201832611515093157.jpg',
    fengge: '漫画改/日常/萌系/校园',
    kbsj:'2019-04-06',
    gengxin:'连载中, 每周六 02:55更新',
    jianjie:'《一个人的○○小日子》讲述改编自《三颗星彩色冒险》的作者カツヲ的另一四格漫画作品。超赞的羞涩少女，为交朋友而努力，不过马上就连唯一的亲友都要失去啦~~',
    player:[],
  },
  {
    title: "天使降临到我身边",
    key: 'dongman12',
    href:"/dongman/12",
    img: 'http://p.xiaomingming.org/FileUpload/2018111610472072223.jpg',
    fengge: '日常/治愈/漫画改/萌系/搞笑',
    kbsj: '2019-01-08',
    gengxin:'已完结, 全13话',
    jianjie:'《天使降临到我身边》讲述与家里蹲死宅女大学生相遇的她居然是天使一般的女小学生！？ 想要和那个超可爱的小妹妹成为朋友的高校短剧即将展开！！改编自日本漫画家椋木 ななつ原作的同名漫画。',
    player:[],
  },
  {
    title: "水果篮子 (2019)",
    key: 'dongman13',
    href:"/dongman/13",
    img: 'http://p.xiaomingming.org/FileUpload/20191251505461272.jpg',
    fengge: '漫画改/日常/萌系/校园',
    kbsj: '2019-04-06',
    gengxin:'连载中, 每周六 01:23更新',
    jianjie:'《水果篮子》讲述高中生本田透在失去了自己唯一亲人的母亲之后过起了独自一人的帐篷生活。但是，透安扎帐篷的地方刚好就是历史渊源的家族草摩家的领地之内！在草摩紫吴的邀请下成为了草摩家佣人的透，居然要与学校里王子般存在的草摩由希、以及视由希为眼中钉的草摩夹这两人一起生活。然而，透却仍未知晓。草摩家自从数百年前起就被忌讳的诅咒所束缚的事实',
    player:[],
  },
  {
    title: "精灵宝可梦 日月",
    key: 'dongman14',
    href:"/dongman/14",
    img: 'http://pic.xiaomingming.org/FileUpload/201691218524642755.jpg',
    fengge: '治愈/游戏改',
    kbsj: '2016-11-17',
    gengxin:'连载中, 每周四更新',
    jianjie:'《宠物小精灵 太阳/月亮》讲述新篇章将于2016年11月放送开始，故事发生在阿罗拉地区，以美国夏威夷为原型，作为此次游戏的冒险舞台，由气候温暖的岛屿所组成，以自然资源丰富的4个岛屿和1个人工岛屿为中心。',
    player:[],
  },
  {
    title: "中二病也要谈恋爱！恋",
    key: 'dongman15',
    href:"/dongman/15",
    img: 'http://pic.xiaomingming.org/FileUpload/4467.jpg',
    fengge: '搞笑/恋爱',
    kbsj: '2014-01-08',
    gengxin:'已完结, 全13话 ',
    jianjie:'由于各种原因导致失去住所的六花开始寻找新家，但过程并不顺利，最终来到了勇太的家里。然而，勇太的家人却留下勇太一个人到雅加达去了。现在开始的同栖生活！？这样想着心跳不已的两个人。但此时樟叶为了迎考而回到了家中。不知应该感到安心还是遗憾，3人开始了奇妙的共同生活。另一方面，原小鸟游家搬进了新的住户。那是以前勇太曾经憧憬的，自称为魔法魔王少女、索非亚琳·SP·撒旦7世的七宫智音……如此这般，仍然完全称不上普通的、勇太的高二第一学期开始了。 ',
    player:[],
  },
  {
    title: "OVERLORD Ⅲ",
    key: 'dongman16',
    href:"/dongman/16",
    img: 'http://p.xiaomingming.org/FileUpload/20184421312852362.jpg',
    fengge: '小说改/奇幻/智斗/战斗/魔法',
    kbsj:'2018-07-10',
    gengxin:'已完结, 全13话 ',
    jianjie:'《Overlord不死者之王 第三季》讲述制作决定！2018年7月播出。曾经的超人气网络游戏YGGDRASIL，迎来了终止运行的一天。青年铃木悟正在公会中等待服务器关闭强制下线，但等到营运时间结束，玩家角色却无法登出游戏。铃木悟以骷髅外表的最强魔法师形态，凭借游戏角色飞鼠的身份和整个公会一起穿越到异世界。此时，NPC们也突然拥有了独立思想，飞鼠率领的公会安兹乌尔恭将展开前所未有的奇幻传说。',
    player:[],
  },
  {
    title: "黑色四叶草",
    key: 'dongman17',
    href:"/dongman/17",
    img: 'http://p.xiaomingming.org/FileUpload/20171041463530516.jpg',
    fengge: '战斗/热血/魔法/漫画改',
    kbsj: '2017-10-03',
    gengxin:'连载中, 每周二18:25更新 ',
    jianjie:'《黑色五叶草》讲述改编自田畠裕基原作漫画。在一个魔法等於一切的世界里，身为孤儿的亚斯塔虽然天生就没有魔力，但仍毫不怠懈地努力锻鍊自己。他和同为孤儿的好友尤诺立志要一起竞争魔法帝的宝座。在魔法书授与仪式中，尤诺得到了传说中的四叶魔导书，而亚斯塔则得到了反魔法的五叶魔导书。之後两人还一起去参加魔法骑士团的入团考试，亚斯塔在历经一番波折後，总算是成为「黑色暴牛骑士团」的一员',
    player:[],
  },
]